### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by aaron13ps** [x3chaos/RTD#2]
{player} has an issue: {player} pulls the resulting name after being modified by a plugin. This makes other plugins not work with that name.
Here is an example
Config:

```
clear:
    - console=/clear {player} flintandsteel
```

Console:

06.04 07:47:23 [Server] INFO Error: Player not found.
06.04 07:47:23 [Server] INFO Command: /clear §9[Owner]§5§cAaron13ps§9§r flintandsteel

I believe its trying to use the modified name (§9[Owner]§5§cAaron13ps§9§r) instead of the root name (Aaron13ps)

**Comment by x3chaos** [comment]
Should be fixed now :)
